# Generated by Django 3.2.5 on 2021-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_artist_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', unique=True),
        ),
    ]
