# Generated by Django 3.2.5 on 2021-07-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='users.crew'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='fb_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='inst_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
