# Generated by Django 3.2.5 on 2021-07-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='8E9v0J', max_length=6, unique=True),
        ),
    ]
