# Generated by Django 3.2.5 on 2021-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
