# Generated by Django 3.2.5 on 2021-08-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210801_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-uploaded',)},
        ),
    ]
